version: '3.8'

services:
  router:
    image: ghcr.io/apollographql/router:v2.3.0
    ports:
      - "4000:4000"
    volumes:
      - ./router/supergraph.graphql:/dist/config/supergraph.graphql
    command: --supergraph /dist/config/supergraph.graphql
    depends_on:
      - product
      - review
      - shipping

  product:
    build:
      context: ./product
      dockerfile: Dockerfile  # Optional if Dockerfile is named "Dockerfile"
    ports:
      - "8081:8081"

  review:
    build:
      context: ./review
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  shipping:
    build:
      context: ./shipping
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
