version: '3.8'

services:
  router:
    image: ghcr.io/apollographql/router:v2.3.0
    ports:
      - "4000:4000"
    volumes:
      - ./router/supergraph.graphql:/dist/config/supergraph.graphql
      - ./router/router-config.yaml:/dist/config/router.yaml
    command: [
      "--dev",
      "-c",
      "config/router.yaml",
      "-s",
      "config/supergraph.graphql"
    ]
    depends_on:
      - product
      - review
      - shipping

  product:
    build:
      context: ./product
      dockerfile: Dockerfile  # Optional if Dockerfile is named "Dockerfile"
    ports:
      - "8081:8081"

  review:
    build:
      context: ./review
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_NAME: reviews_db
    depends_on:
      - db

  shipping:
    build:
      context: ./shipping
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reviews_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"