package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"

	"github.com/xamenyap/graphql-federation/review/graph/model"
	"github.com/xamenyap/graphql-federation/review/loader"
)

// FindProductByID is the resolver for the findProductByID field.
func (r *entityResolver) FindProductByID(ctx context.Context, id string) (*model.Product, error) {
	reviewsLoader := loader.From(ctx)
	reviews, err := reviewsLoader.Load(ctx, id)
	if err != nil {
		return nil, err
	}

	var reviewModels []*model.Review
	for _, review := range reviews {
		reviewModels = append(reviewModels, &model.Review{
			ID:   review.ID,
			Body: review.Body,
		})
	}

	return &model.Product{
		ID:      id,
		Reviews: reviewModels,
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
