package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"

	"github.com/xamenyap/graphql-federation/review/graph/model"
)

// FindProductByID is the resolver for the findProductByID field.
func (r *entityResolver) FindProductByID(ctx context.Context, id string) (*model.Product, error) {
	var reviews []*model.Review
	switch id {
	case "1":
		reviews = []*model.Review{
			{
				ID:   "1",
				Body: "very good product",
			},
			{
				ID:   "2",
				Body: "Decent product, but I found better on other platforms",
			},
		}
	case "2":
		reviews = []*model.Review{
			{
				ID:   "3",
				Body: "Very mediocre, should not buy",
			},
		}
	}
	return &model.Product{
		ID:      id,
		Reviews: reviews,
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
