package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"fmt"

	"github.com/xamenyap/graphql-federation/shipping/graph/model"
)

// EstimatedDeliveryTime is the resolver for the estimatedDeliveryTime field.
func (r *productResolver) EstimatedDeliveryTime(ctx context.Context, obj *model.Product, federationRequires map[string]any) (*string, error) {
	panic(fmt.Errorf("not implemented: EstimatedDeliveryTime - estimatedDeliveryTime"))
}

// Product returns ProductResolver implementation.
func (r *Resolver) Product() ProductResolver { return &productResolver{r} }

type productResolver struct{ *Resolver }
