package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"

	"github.com/xamenyap/graphql-federation/product/graph/model"
)

// ProductList is the resolver for the productList field.
func (r *queryResolver) ProductList(ctx context.Context) ([]*model.Product, error) {
	weight := 0.25
	return []*model.Product{
		{
			ID:     "1",
			Name:   "sample-product-1",
			Price:  1.5,
			Weight: &weight,
		},
		{
			ID:     "2",
			Name:   "sample-product-2",
			Price:  2.5,
			Weight: &weight,
		},
		{
			ID:    "3",
			Name:  "sample-product-3",
			Price: 5.5,
		},
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
